name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-ubuntu2004-ansible:$(date +%s)
      
    - name: Collect docker logs on failure
#       if: failure()
      uses: jwalton/gh-docker-logs@v1
      with:
        dest: './logs'
    - name: Tar logs
#       if: failure()
      run: tar cvzf ./logs.tgz ./logs
    - name: Upload logs to GitHub
#       if: failure()
      uses: actions/upload-artifact@master
      with:
        name: logs.tgz
        path: ./logs.tgz

